# Create a pod that reads and writes to the
# NFS server via an NFS volume.

kind: Job
apiVersion: batch/v1
metadata:
  name: elastic-backup
spec:
  template:
    spec:
      # Add the server as an NFS volume for the pod
      volumes:
        - name: nfs-volume
          nfs: 
            # URL for the NFS server
            server: 10.1.5.158 # Change this!
            path: /
      # In this container, we'll mount the NFS volume
      # and write the date to a file inside it.
        - name: config
          configMap:
            name: elastic-backup-config
            items:
            - key: "config.yaml"
              path: "config.yaml"
            - key: "backup.yaml"
              path: "backup.yaml"
            - key: "restore.yaml"
              path: "restore.yaml"
            - key: "delete.yaml"
              path: "delete.yaml"
      containers:
        - name: elastic-backup
          image: elastic-backup:2.1
          # Mount the NFS volume in the container
          volumeMounts:
            - name: nfs-volume
              mountPath: /var/nfs
            - name: config
              mountPath: "/config"
              readOnly: true
          env:
          - name: PASSWORD
            value: test
          - name: STATE
            value: backup
          - name: ELASTIC_HOST
            value: elasticsearch
          - name: PORT
            value: "9200"
          - name: SEARCH_PATH
            value: indices
          - name: REPO
            value: elastic
          - name: ENCRYPTION
            value: "true"
          - name: STOARGEPATH
            value: elastic
          
      restartPolicy: Never
  backoffLimit: 4