---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-backup-config
data:
  config.yaml: |
    ---
    client:
      hosts:
        - elasticsearch
      port: 9200
    logging:
      loglevel: INFO

  backup.yaml: |
    ---
    actions:
      1:
        action: snapshot
        description: >-
          Snapshot selected indices to 'repository' with the snapshot name or name
          pattern in 'name'.  Use all other options as assigned
        options:
          repository: elastic
          # Leaving name blank will result in the default 'curator-%Y%m%d%H%M%S'
          name: logs-%Y-%m-%d-%H-%M
          wait_for_completion: True
          max_wait: 3600
          wait_interval: 10
        filters:
        - filtertype: pattern
          kind: prefix
          value: restored-
          exclude: true
  
  restore.yaml: |
    ---
    actions:
      1:
        action: restore
        description: >-
          Restore all indices in the most recent snapshot with state SUCCESS.  Wait
          for the restore to complete before continuing.  Do not skip the repository
          filesystem access check.  Use the other options to define the index/shard
          settings for the restore.
        options:
          repository: elastic
          # If name is blank, the most recent snapshot by age will be selected
          name:
          # If indices is blank, all indices in the snapshot will be restored
          indices:
          rename_pattern: '(.+)'
          rename_replacement: 'restored_$1'
          wait_for_completion: True
          max_wait: 3600
          wait_interval: 10
        filters:
        - filtertype: state
          state: SUCCESS
          exclude:

  delete.yaml: |
    ---
    actions:
      1:
        action: delete_snapshots
        description: "Delete selected snapshots from 'repository'"
        options:
          repository: elastic
          retry_interval: 120
          retry_count: 3
          ignore_empty_list: True
        filters:
          - filtertype: pattern
            kind: prefix
            value: audit-
            exclude: True
          - filtertype: age
            source: creation_date
            direction: older
            unit: minutes
            unit_count: 1
            exclude: False